// HeadTrack tuning surface. Adjust values here instead of touching scene code.
export const headTrackConfig = {
  enabled: {
    // Default HeadTrack state when entering Single Cube Orbit View.
    defaultOn: false,
    // Use pointer input only after secure-context camera/model startup failures.
    fallbackToPointer: true,
  },
  performance: {
    // Lower resolution reduces TFJS inference cost and stutter on slower devices.
    video: {
      width: 320,
      height: 240,
      frameRate: 24,
    },
    // Lower maxFps reduces GPU/CPU load. Higher maxFps updates tracking more often.
    maxFps: 24,
  },
  tracking: {
    // Higher scoreThreshold is stricter but may drop faces more often.
    scoreThreshold: 0.85,
    // Lower smoothing ms reacts faster. Higher smoothing ms reduces jitter.
    smoothEyeMs: 45,
    smoothDistanceMs: 120,
    smoothInputMs: 70,
    // Baseline face distance used to normalize forward/back movement.
    defaultDistance: 0.12,
    // Adds a small nose/eye offset signal for head yaw. Raise carefully to avoid jitter.
    horizontalYawWeight: 0.35,
    // Delay before returning to neutral when no face is detected.
    noFaceHoldMs: 400,
  },
  movement: {
    // Clamp normalized head input before it reaches the camera adapter.
    inputClamp: {
      x: [-1, 1],
      y: [-1, 1],
      z: [0.65, 1.45],
    },
    // Raise x for stronger left/right response. Raise y for stronger up/down response.
    headInputScale: {
      x: 2.0,
      y: 2.5,
    },
    // Flip axes if real-device movement feels reversed.
    invertX: false,
    invertY: false,
    // Raise yawScale for stronger horizontal orbit around the cube.
    yawScale: 0.86,
    // Raise y for more top/bottom reveal. Raise z for stronger forward/back distance.
    positionScale: {
      y: 120,
      z: 70,
    },
  },
  camera: {
    // Raise fovScale for stronger depth/zoom feel from forward/back movement.
    fovScale: 0.08,
    // Lower responseMs follows faster. Higher responseMs feels smoother.
    responseMs: 25,
    // Lower neutralReturnMs snaps back faster when tracking returns to center.
    neutralReturnMs: 100,
  },
} as const;

export const cubeOrbitParallaxConfig = {
  defaultEnabled: headTrackConfig.enabled.defaultOn,
  fallbackToPointer: headTrackConfig.enabled.fallbackToPointer,
  tracking: {
    scoreThreshold: headTrackConfig.tracking.scoreThreshold,
    video: headTrackConfig.performance.video,
    maxFps: headTrackConfig.performance.maxFps,
    smoothEyeMs: headTrackConfig.tracking.smoothEyeMs,
    smoothDistanceMs: headTrackConfig.tracking.smoothDistanceMs,
    smoothInputMs: headTrackConfig.tracking.smoothInputMs,
    defaultDistance: headTrackConfig.tracking.defaultDistance,
    horizontalYawWeight: headTrackConfig.tracking.horizontalYawWeight,
  },
  inputClamp: headTrackConfig.movement.inputClamp,
  camera: {
    headInputScale: headTrackConfig.movement.headInputScale,
    invertX: headTrackConfig.movement.invertX,
    invertY: headTrackConfig.movement.invertY,
    yawScale: headTrackConfig.movement.yawScale,
    positionScale: headTrackConfig.movement.positionScale,
    fovScale: headTrackConfig.camera.fovScale,
    responseMs: headTrackConfig.camera.responseMs,
    neutralReturnMs: headTrackConfig.camera.neutralReturnMs,
  },
  noFaceHoldMs: headTrackConfig.tracking.noFaceHoldMs,
} as const;
export const cubeSceneTheme = {
  background: "#d6d6d6",
  rendering: {
    toneMappingExposure: 0.9,
  },
  fog: {
    density: 0.0004,
  },
  camera: {
    fov: 20,
    near: 0.5,
    far: 2000,
    distance: 500,
    minDistance: 250,
    maxDistance: 800,
    offset: [108, 90, 108],
  },
  controls: {
    dampingFactor: 0.1,
    rotateSpeed: 0.55,
    zoomSpeed: 0.75,
    panSpeed: 0.65,
  },
  searchHighlightZoom: {
    durationMs: 500,
    distanceMultiplier: 0.7,
    targetPull: 0.12,
  },
  mapView: {
    baseColor: "#bfc1c3",
    opacityMaskStrength: 0,
    emissiveStrength: 0,
  },
  orbitView: {
    focusedScale: 4.5,
    cameraDistance: 500,
    minDistance: 500,
    maxDistance: 700,
    cameraOffset: [64, 42, 76],
    cameraTransitionDurationMs: 420,
    opacityMaskSrc: "/assets/models/cube%20mask%20textures/Cube%20Opacity%20Mask_2.png",
    opacityMaskTransitionLerp: 0.08,
    autoRotate: {
      enabled: true,
      speed: 0.55,
      resumeDelayMs: 1500,
    },
    parallax: cubeOrbitParallaxConfig,
    frontViewFade: {
      strength: 0.12,
      power: 2.4,
      alphaMultiplier: 0.9,
      saturationMultiplier: 0.94,
      transitionLerp: 0.08,
    },
    storyCube: {
      scale: 0.9,
      textureSrcs: [
        "/assets/models/story%20thumbnail/T_WorkingMom.png",
        "/assets/models/story%20thumbnail/T_Setlog.png",
        "/assets/models/story%20thumbnail/T_Senior.png",
        "/assets/models/story%20thumbnail/T_NoobDad.png",
        "/assets/models/story%20thumbnail/T_Puppy.png",
        "/assets/models/story%20thumbnail/T_Tech.png",
        "/assets/models/story%20thumbnail/T_Blog.png",
        "/assets/models/story%20thumbnail/T_Toon.png",
        "/assets/models/story%20thumbnail/T_AIKun.png",
        "/assets/models/story%20thumbnail/T_Blind.png",
        "/assets/models/story%20thumbnail/T_Shorts.png",
        "/assets/models/story%20thumbnail/T_Photo.png",
      ],
    },
  },
  cube: {
    model: {
      src: "/assets/models/cube_blender.glb",
      opacityMaskSrc: "/assets/models/cube%20mask%20textures/Cube%20Opacity%20Mask.png",
      emissiveMaskSrc: "/assets/models/cube%20mask%20textures/Cube%20Emissive%20Mask.png",
    },
    radius: 0.45,
    segments: 2,
    opacity: 1,
    playbookThumbnailOpacity: 0.92,
    glass: {
      color: "#f2f1ff",
      roughness: 0.02,
      edgeRoughness: 0.2,
      edgeWidth: 0.14,
      edgeFalloffPower: 1.8,
      fresnelPower: 3,
      iridescence: 0.48,
      iridescenceIOR: 1.3,
      iridescenceThicknessRange: [180, 360] as const,
      ior: 1.45,
      transmission: 0.97,
      thickness: 0.8,
      opacity: 1,
      envMapIntensity: 1.35,
      specularIntensity: 1,
      attenuationColor: "#f7f3ff",
      attenuationDistance: 7.5,
      thumbnailScale: 0.9,
    },
    shader: {
      roughness: 0.32,
      metallic: 0,
      baseColorOverride: null as string | null,
      palette: ["#c1fff4", "#dafbae", "#b4aefa", "#b4d3ff", "#a4eaff", "#c8ffc1"],
      paletteMode: "spatial",
      subsurfaceColor: "#f7fffb",
      subsurfaceStrength: 0.16,
      wrap: 0.12,
      rimStrength: 0.18,
      rimPower: 2.4,
      transmissionStrength: 0.08,
      glassStrength: 0.78,
      shadowStrength: 0.32,
      shadowSoftness: 0.58,
      shadowLift: 0.38,
      baseSaturation: 1.0,
      edgeSaturation: 1.18,
      centerWhiteness: 0.05,
      faceEdgePower: 1.35,
      colorContrast: 1.07,
      colorVibrance: 0.2,
      emissiveColor: "#d7e6ff",
      emissiveStrength: 0.14,
    },
    enterDelay: 220,
    enterStagger: 24,
    enterMaxStagger: 540,
    enterDuration: 520,
  },
  grid: {
    color: 0xc3c1c7,
    opacity: 0.4,
    backfaceHideEpsilon: 0.01,
  },
  axisGuide: {
    lineColor: 0x52606a,
    tickColor: 0x52606a,
    lineOpacity: 0.58,
    tickOpacity: 0.5,
    axisPadding: 18,
    arrowLength: 4.2,
    arrowRadius: 1.1,
    tickLength: 3.8,
    labelOffset: 7,
    titleOffset: 12,
    labelHeight: 2.94,
    titleHeight: 3.92,
    labelMaxCanvasWidth: 220,
    titleMaxCanvasWidth: 260,
    labelFontSize: 13,
    titleFontSize: 17,
    fontFamily: "Pretendard, Inter, sans-serif",
    labelTextColor: "#34404a",
    titleTextColor: "#20272e",
    labelBackgroundColor: "rgba(255, 255, 255, 0.62)",
    titleBackgroundColor: "rgba(255, 255, 255, 0.76)",
    labelBorderColor: "rgba(255, 255, 255, 0.8)",
    axes: {
      x: {
        title: "Feature",
        values: [
          "파워트레인",
          "배터리·항속거리",
          "V2L·V2G",
          "구동·섀시",
          "ADAS",
          "디스플레이·HUD",
          "인포테인먼트·OTA",
          "실내 공간·시트",
          "AI 어시스턴트",
          "에너지·경로 최적화",
          "스마트홈·원격 모니터링",
          "V2X·자율주행",
        ],
      },
      y: {
        title: "Hardware",
        values: [
          "캐스퍼",
          "모닝",
          "레이",
          "아반떼",
          "K3",
          "코나",
          "니로",
          "EV3",
          "아이오닉 6",
          "스포티지",
          "투싼",
          "K5",
        ],
      },
      z: {
        title: "User Story",
        values: [
          "워킹맘",
          "신혼부부",
          "사회초년생",
          "50대 빈둥지 아빠",
          "은퇴 부부",
          "캠핑 패밀리",
          "반려견 여행족",
          "EV 충전 불안러",
          "고령 단독 운전자",
          "차박 싱글",
          "장거리 영업직",
          "대리운전 불안 오너",
        ],
      },
    },
  },
  hover: {
    spreadDistance: 18.2,
    spreadFalloffUnits: 8.5,
    spreadMinInfluence: 0.18,
    dimScale: 0.75,
    hoverScale: 1.08,
    dimOpacityMultiplier: 1,
    positionLerp: 0.09,
    scaleLerp: 0.14,
    materialLerp: 0.12,
    collisionStep: 0.05,
    collisionPadding: 0.01,
    boundaryPadding: 0,
    highlightOpacity: 1,
    searchHighlightHoverScale: 1.08,
    filteredHighlightHoverScale: 1.18,
  },
  hoverGlow: {
    outlineColor: 0xffffff,
    glowColor: 0xd7e6ff,
    outlineOpacity: 0.95,
    glowOpacity: 0.7,
    outlineThickness: 1.0,
    glowRadius: 50,
    noiseStrength: 0.5,
    flowSpeed: 0.05,
    pulseSpeed: 1.35,
    fadeLerp: 0.16,
  },
  lights: {
    ambient: {
      color: 0xffffff,
      intensity: 0.35,
    },
    directional: [
      { color: 0xffffff, position: [2.2, 3.4, 2.1], intensity: 1.2 },
      { color: 0xffffff, position: [-2, 1.4, -2.6], intensity: 0.35 },
      { color: 0xffffff, position: [0.2, -2, 1.2], intensity: 0.2 },
    ],
  },
} as const;
